modules/MubAdmin/modules/furniture/models/Product.php
<?php

namespace app\modules\MubAdmin\modules\furniture\models;

use Yii;
use app\models\MubUser;
use app\models\State;
use yz\shoppingcart\CartPositionTrait;
use yz\shoppingcart\CartPositionInterface;
/**
/**
 * This is the model class for table "product".
 *
 * @property integer $id
 * @property integer $mub_user_id
 * @property string $product_name
 * @property string $product_slug
 * @property string $product_description
 * @property string $product_excerpt
 * @property string $product_type
 * @property integer $stock_quantity
 * @property integer $product_code
 * @property string $brand_name
 * @property integer $price
 * @property integer $cell_price
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $del_status
 *
 * @property PostPingStats[] $postPingStats
 * @property MubUser $mubUser
 * @property ProductAttribute[] $productAttributes
 * @property ProductCategory[] $productCategories
 * @property ProductImages[] $productImages
 * @property ProductTags[] $productTags
 * @property UserAttribute[] $userAttributes
 */
class Product extends \app\components\Model implements CartPositionInterface
{
    use CartPositionTrait;

    public function getPrice()
    {
        return $this->mrp;
    }


    public static function tableName()
    {
        return 'product';
    }

    public function rules()
    {
        return [
            [['mrp','sell_price','product_name'],'required'],
            [['hsn_code', 'manufacture_SKU','manufacture_SKU_name','description', 'status', 'del_status','inner_spec_of_seat','seat_mattress','arm_rest','time_to_ship','product_group','furniture_material','fabric_type','foam_type_density','assembly','warranty','specification_general','furniture_weight','box_content','box_count','stock_quantity', 'mrp', 'sell_price', 'width','height','depth','base_cost','seating_height','product_slug'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['mub_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MubUser::className(), 'targetAttribute' => ['mub_user_id' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mub_user_id' => 'Mub User ID',
            'hsn_code' => 'hsn_code',
            'manufacture_SKU' => 'manufacture_SKU',
            'manufacture_SKU_name' => 'manufacture_SKU_name',
            'product_name' => 'Product Name',
            'product_slug' => 'product_slug',
            'description' => 'Description',
            'inner_spec_of_seat' => 'inner_spec_of_seat',
            'seat_mattress' => 'seat_mattress',
            'arm_rest' => 'arm_rest',
            'base_cost' => 'base_cost',
            'stock_quantity' => 'Stock Quantity',
            'base_cost' => 'Base Cost',
            'sell_price' => 'Sell Price',
            'mrp' => 'MRP',
            'time_to_ship' => 'time_to_ship',
            'width' => 'width',
            'depth' => 'depth',
            'height' => 'height',
            'product_group' => 'product_group',
            'furniture_material' => 'furniture_material',
            'fabric_type' => 'fabric_type',
            'foam_type_density' => 'foam_type_density',
            'assembly' => 'assembly',
            'warranty' => 'warranty',
            'specification_general' => 'specification_general',
            'furniture_weight' => 'furniture_weight',
            'seating_height'=> 'seating_height',
            'box_content' => 'box_content',
            'box_count' => 'box_count',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'del_status' => 'Del Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */

     public function getId()
    {
        return $this->id;
    }

    public function getPostPingStats()
    {
        return $this->hasMany(PostPingStats::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMubUser()
    {
        return $this->hasOne(MubUser::className(), ['id' => 'mub_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductAttributes()
    {
        return $this->hasMany(ProductAttributes::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(ProductCategories::className(), ['product_id' => 'id'])->where(['product_categories.del_status' => '0']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductImages()
    {
        return $this->hasMany(ProductImages::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductTags()
    {
        return $this->hasMany(ProductTags::className(), ['product_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserAttributes()
    {
        return $this->hasMany(UserAttribute::className(), ['product_id' => 'id']);
    }
}

modules/MubAdmin/modules/furniture/controllers/ProductController.php
<?php

namespace app\modules\MubAdmin\modules\furniture\controllers;

use Yii;
use app\modules\MubAdmin\modules\furniture\models\Product;
use app\modules\MubAdmin\modules\furniture\models\ProductSearch;
use app\modules\MubAdmin\modules\furniture\models\ProductProcess;
use app\modules\MubAdmin\modules\furniture\models\ProductImages;
use yii\web\UploadedFile;

use yii\helpers\FileHelper;
use app\components\MubController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;

/**
 * ProductController implements the CRUD actions for Product model.
 */
class ProductController extends MubController
{
    public function getPrimaryModel()
   {
        return new Product();
   }

   public function getProcessModel()
   {
        return new ProductProcess();
   }

   public function getSearchModel()
   {
        return new ProductSearch();
   }
    
    public function actionProductImage($userId)
   {
    if (\Yii::$app->request->isAjax) {
      $model = new ProductImages();

      $imageFile = UploadedFile::getInstance($model, 'thumbnail_url');

      $directory = \Yii::getAlias('@app/images/product/');
      if (!is_dir($directory)) {
          FileHelper::createDirectory($directory);
      }

      if ($imageFile) {
          $uid = uniqid(time(), true);
          $fileName = $uid . '.' . $imageFile->extension;
          $filePath = $directory . $fileName;
          $rid = \Yii::$app->getRequest()->getQueryParam('product');
          if ($imageFile->saveAs($filePath)) {
              $path = '/images/product/'.$fileName;
              $model->mub_user_id = $userId;
              $model->product_id = ($rid == '') ? NULL :$rid;
              $model->title = $uid . '.' . $imageFile->extension;
              $model->full_path = $path;
              $model->thumbnail_url = $path;
              if(!$model->save())
              {
                p($model->getErrors());
              }
              
              $successPath = '/images/done.png';
              return Json::encode([
                  'files' => [
                      [
                          'name' => $fileName,
                          'size' => $imageFile->size,
                          'url' => $successPath,
                          'thumbnailUrl' => $successPath,
                          'deleteUrl' => 'image-delete?name=' . $fileName,
                          'deleteType' => 'POST',
                      ],
                  ],
              ]);
          }
      }
      return '';
    }else
    {
      return 'go away';
    }
  }

  public function actionImageDelete($name)
  {
     if (\Yii::$app->request->isAjax) {
      $stateId = \Yii::$app->request->getQueryParam('state');
      $directory = \Yii::getAlias('@app/images/product') . DIRECTORY_SEPARATOR;
      if (is_file($directory.$name)) 
      {
          if(unlink($directory . $name))
          {
            $productImages = new \app\modules\MubAdmin\modules\item\models\ProductImages();
            $success = $productImages::deleteAll(['title' => $name]);
            if($success)
            {
              return 'Image Deleted Successfully'; 
            }
          }else
          {
            return 'There was a problem deleting the Image';
          }
      }
      else
      {
        $productImages = new \app\modules\MubAdmin\modules\item\models\ProductImages();
        $success = $productImages::deleteAll(['title' => $name]);
        if($success)
        {
          return 'Image Deleted from Records'; 
        }
      }
      
  }else
  {
    return 'Go Awayyyy!';
  }
}
}

modules/MubAdmin/modules/furniture/views/product/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\fileupload\FileUploadUI;
use app\helpers\ImageUploader;
use app\modules\MubAdmin\modules\furniture\models\ProductImages;
use yii\web\JsExpression;
use dosamigos\tinymce\TinyMce;
use wbraganca\dynamicform\DynamicFormWidget;

$productImages = new ProductImages();
$images = $productImages::find()->where(['product_id' => $product->id,'del_status' => '0'])->all();
$mubUserId = \app\models\User::getMubUserId();
/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\furniture\products\Product */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="product-form">
<div class="row">
    <div class="col-md-10 col-md-offset-1">


    <h5><b>Product Images</b></h5>
    <?= FileUploadUI::widget([
    'model' => $productImages,
    'attribute' => 'thumbnail_url',
    'url' => ['product/product-image', 'userId' => $mubUserId, 'product' => $product->id],
    'gallery' => false,
    'fieldOptions' => [
        'accept' => 'image/*'
    ],
    'clientOptions' => [
        'maxFileSize' => 5000000,
        'load' => true
    ],
    'clientEvents' => [
        'fileuploaddone' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
        'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                            }',
    ],
]); ?>
</div>
</div>

    <?php $form = ActiveForm::begin(); ?>
   <?php if(!empty($images)){?>
    <?php  foreach($images as $key=>$image){

        ?>
    <div id="uploaded<?php echo $key;?>" style="display: inline; margin-right: 10px;">
    <?php echo Html::img(ImageUploader::resizeRender($image->thumbnail_url, '100', '100'),['height'=>100,'width'=>100]);
    echo Html::a(
        Yii::t('app', 'x'),
        '#',
        ["class" => "btn btn-danger del-image","id" => $image->title]);
    ?>
     </div>
     <?php }}?><br/><br/>

  <div class="row">
    <div class="col-md-5 col-md-offset-1">
    <?= $form->field($product, 'hsn_code')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-md-5">
        <?= $form->field($product, 'manufacture_SKU')->textInput();?>
    </div>
  </div>

 <div class="row">
    <div class="col-md-5 col-md-offset-1">
    <?= $form->field($product, 'manufacture_SKU_name')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-md-5">
        <?= $form->field($product, 'product_name')->textInput();?>
    </div>
  </div>

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
        <?= $form->field($product, 'description')->widget(TinyMce::className(), [
        'options' => ['rows' => 6],
        'language' => 'en_GB',
        'clientOptions' => [
            'plugins' => [
                "advlist autolink lists link charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
            ],
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            ]
        ]);?>
        </div>
    </div>


    <div class="row">
      <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'inner_spec_of_seat')->textInput(['maxlength' => true]);?>
       </div>
       <div class="col-md-5">
        <?= $form->field($product, 'seat_mattress')->textInput();?>
       </div>
     </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'arm_rest')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'stock_quantity')->textInput(['maxlength' => true]);?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'base_cost')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'sell_price')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'mrp')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'time_to_ship')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'width')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'depth')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'height')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'product_group')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'furniture_material')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'fabric_type')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'foam_type_density')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'assembly')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'warranty')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'specification_general')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'furniture_weight')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'seating_height')->textInput();?>
       </div>
    </div>

    <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'box_content')->textInput();?>
        </div>
        <div class="col-md-5">
        <?= $form->field($product, 'box_count')->textInput();?>
       </div>
    </div>

   <div class="row">
        <div class="col-md-5 col-md-offset-1">
        <?= $form->field($product, 'status')->dropDownList([ 'active' => 'Active', 'inactive' => 'Inactive', ], ['prompt' => 'Select Status']);?>
      </div>
   </div>

   <div class="row">
    <div class=" col-md-5 col-md-offset-1">
    <?php echo $form->field($productCategories, 'category_id')->checkboxList($allCategory)->label('Select Product Tags'); ?>
   </div>
    </div>
    
    <div class="row">
    <div class="col-md-5 col-md-offset-1">
    <div class="form-group">
        <?= Html::submitButton($product->isNewRecord ? 'Create' : 'Update', ['class' => $product->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);?>
    </div>
    </div>
    </div><br/>
    <?php ActiveForm::end(); ?>

</div>

modules/MubAdmin/modules/furniture/views/product/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\furniture\products\ProductSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($product, 'id') ?>

    <?= $form->field($product, 'mub_user_id') ?>

    <?= $form->field($product, 'product_name') ?>

    <?= $form->field($product, 'product_slug') ?>

    <?= $form->field($product, 'product_description') ?>

    <?php // echo $form->field($product, 'product_excerpt') ?>

    <?php // echo $form->field($product, 'product_type') ?>

    <?php // echo $form->field($product, 'quantity') ?>

    <?php // echo $form->field($product, 'product_code') ?>

    <?php // echo $form->field($product, 'brand_name') ?>

    <?php // echo $form->field($product, 'price') ?>

    <?php // echo $form->field($product, 'cell_price') ?>

    <?php // echo $form->field($product, 'discount_price') ?>

    <?php // echo $form->field($product, 'status') ?>

    <?php // echo $form->field($product, 'created_at') ?>

    <?php // echo $form->field($product, 'updated_at') ?>

    <?php // echo $form->field($product, 'del_status') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/MubAdmin/modules/furniture/views/product/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\MubAdmin\modules\furniture\models\Product */

$this->title = 'Create Product';
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-create">
<div class="col-md-10 col-md-offset-1">
    <h1><?= Html::encode($this->title) ?></h1>
</div>
    <?= $this->render('_form', [
        'product' => $product,
        'allCategory' => $allcategory,
        'productCategories' => $productCategories,
    ]) ?>

</div>

modules/MubAdmin/modules/furniture/views/product/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\MubAdmin\modules\furniture\models\ProductSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Products';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>



    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            // 'mub_user_id',
            'hsn_code',
            'manufacture_SKU',
            'manufacture_SKU_name:ntext',
            'product_name',
            //'product_slug',
            //'description:ntext',
            //'inner_spec_of_seat',
            //'seat_mattress',
            //'arm_rest',
            'stock_quantity',
            'base_cost',
            'sell_price',
            'mrp',
            //'time_to_ship',
            //'width',
            //'depth',
            //'height',
            //'product_group',
            // 'furniture_material',
            'fabric_type',
            //'foam_type_density',
            //'assembly',
            //'warranty',
            //'specification_general',
            //'furniture_weight',
            //'seating_height',
            //'box_content',
            //'box_count',
            'status',
            //'created_at',
            //'updated_at',
            //'del_status',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/MubAdmin/modules/furniture/views/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\furniture\products\Product */

$this->title = 'Update Product: ' . $product->id;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $product->id, 'url' => ['view', 'id' => $product->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'product' => $product,
        'allCategory' => $allcategory,
        'productCategories' => $productCategories,
    ]) ?>

</div>

modules/MubAdmin/modules/furniture/views/product/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $product app\modules\MubAdmin\modules\furniture\models\Product */

$this->title = $product->id;
$this->params['breadcrumbs'][] = ['label' => 'Products', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $product->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $product->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $product,
        'attributes' => [
            'id',
            'mub_user_id',
            'hsn_code',
            'manufacture_SKU',
            'manufacture_SKU_name:ntext',
            'product_name',
            'product_slug',
            'description:ntext',
            'inner_spec_of_seat',
            'seat_mattress',
            'arm_rest',
            'stock_quantity',
            'base_cost',
            'sell_price',
            'mrp',
            'time_to_ship',
            'width',
            'depth',
            'height',
            'product_group',
            'furniture_material',
            'fabric_type',
            'foam_type_density',
            'assembly',
            'warranty',
            'specification_general',
            'furniture_weight',
            'seating_height',
            'box_content',
            'box_count',
            'status',
            'created_at',
            'updated_at',
            'del_status',
        ],
    ]) ?>

</div>